services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?MYSQL_DATABASE is required}
      MYSQL_USER: ${MYSQL_USER:?MYSQL_USER is required}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is required}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}

    volumes:
      - mariadb:/var/lib/mysql

    networks:
      - inception

    restart: unless-stopped


  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?MYSQL_DATABASE is required}
      MYSQL_USER: ${MYSQL_USER:?MYSQL_USER is required}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is required}

      DOMAIN_NAME: ${DOMAIN_NAME:?DOMAIN_NAME is required}

      WP_ADMIN_USER: ${WP_ADMIN_USER:?WP_ADMIN_USER is required}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD:?WP_ADMIN_PASSWORD is required}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL:?WP_ADMIN_EMAIL is required}

      WP_USER: ${WP_USER:?WP_USER is required}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD:?WP_USER_PASSWORD is required}
      WP_USER_EMAIL: ${WP_USER_EMAIL:?WP_USER_EMAIL is required}

    depends_on:
      - mariadb

    volumes:
      - wordpress:/var/www/html

    networks:
      - inception

    restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx

    ports:
      - "443:443"

    volumes:
      - wordpress:/var/www/html

    depends_on:
      - wordpress

    networks:
      - inception

    restart: unless-stopped


networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR:?DATA_DIR is required}/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR:?DATA_DIR is required}/wordpress
