services:

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - inception

    restart: unless-stopped


  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      DOMAIN_NAME: ${DOMAIN_NAME}

      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}

    depends_on:
      - mariadb

    volumes:
      - wordpress:/var/www/html

    networks:
      - inception

    restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx

    ports:
      - "443:443"

    volumes:
      - wordpress:/var/www/html

    depends_on:
      - wordpress

    networks:
      - inception

    restart: unless-stopped


networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb

  wordpress:
    name: wordpress